### ISSUE TITLE
Research autogenerating lists

### ISSUE THREAD

**Issue by jungshadow** [it-dept-cis/Essential-Guide-to-Election-Security#11]
For instance, the bp_index would autobuild from the BPs. Same for hyperlinks, acronyms and definitions.

**Comment by mike-garcia** [comment]
@jungshadow we learn anything about this? I'm thinking not worth the squeeze but if you disagree we can keep looking. Either close or change to launch milestone.

**Comment by jungshadow** [comment]
Sadly, I don't see how this is possible outside of writing a python script that has to be run before the build (and added to the repository). We did this with the Voting Information Project, but seems like a hassle here. IMHO, I'd close this.

**Comment by mike-garcia** [comment]
done. there may be a day, but I'm making as wontfix rather than enhancement
