### ISSUE TITLE
worksheet download not available in PDF

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#127]
links to download the excel worksheets function properly on RTD, but are not linked in the PDF. See worksheets.rst line 14: There are 10 total worksheets. Download the full set of worksheets in :download:`xlsx <../_downloads/EGES_level_1_baseline_wksts.xlsx>`.

**Comment by jungshadow** [comment]
Sadly, there are only a couple of options here:

1. We change the `download` role to a regular `ref` and point to a URL where the worksheet is hosted (e.g., CIS website, GitHub location).
2. We suppress the `download` role in the PDF (i.e., see the `only` directive in [the Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#referencing-downloadable-files)).

Happy to implement either one, but I imagine we want the worksheet to be link-able, so number one seems to be our best option.

**Comment by mike-garcia** [comment]
That is sad. Let’s go with 1 and link to GitHub. Maybe we come up with something more elegant in the future

**Comment by jungshadow** [comment]
I opted for Option 3: Add `_worksheets` folder into the `html_extra_path` setting which pulls it into the build as a separate directory. I added an absolute link to its final resting place on Read the Docs. This should allow it to permanently live on the RTD.io domain space and be accessible to the PDF. Only drawback is this will only work after the next deploy to main.
