### ISSUE TITLE
Look for ways to improve readability, layout, or design

### ISSUE THREAD

**Issue by jungshadow** [it-dept-cis/Essential-Guide-to-Election-Security#13]

**Comment by jungshadow** [comment]
@mike-garcia I think I already have something for this. I'd like to see something you need made into a table, first, though, just to experiment with the styling.

**Comment by mike-garcia** [comment]
docs/source/BPs/encryption.rst has a simple table, probably not the thing we care about

my concept for the BIG table is to provide all the best practices with a very short (1 phrase/sentence) description, then mapping out to maturities in a prioritized order. This could get unwieldy quick, so I want to think carefully about it. It is bps in rows with maturities in columns and prioritization in a cell? Or 3 tables, one for each maturity? Can we make it a checklist or some other tool that would be useful for tracking progress? 

Many ways to go and this is not yet clear in my head. I could also see things outside RTD that might be good for parts of this (like task list building) that we can talk about and put on a future dev list. Then we could do more basic tables for soft launch

**Comment by mike-garcia** [comment]
I think this is stale and we can close. if you agree, shut it down!

**Comment by jungshadow** [comment]
Agreed.
