### ISSUE TITLE
Remove ACTIONS Section Heading from All BPs

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#174]
I think I created this heading when the guide was in a different state. I think it's overcoming by events at this point and is mostly just a placeholder for content that will never appear.

**Comment by mike-garcia** [comment]
I guess my question is why would we get rid of the actions header? It's pretty useful for linking and breaks up the content.

**Comment by mike-garcia** [comment]
Okay I think I'm going to leave this in for now. If you disagree, let's discuss and plan it for the next update.
