### ISSUE TITLE
New BP: Segment Data Processing and Storage Based on Sensitivity

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#177]
Suggest that this should NOT be a BP. It's a direct copy / paste from a CIS Control. Seems odd and I think we should discuss more. 

3.12 Segment Data Processing and Storage Based on Sensitivity Network -Protect- • •
Segment data processing and storage based on the sensitivity of the data. Do not process sensitive data on enterprise assets intended 
for lower sensitivity data.

**Comment by JTAGulous** [comment]
@mike-garcia I wanna get this one going if you disagree. Is there any way to have some more backstory on this one? What's driving this as a new BP?

**Comment by mike-garcia** [comment]
It's in there because it's a control! I took the top 20 most efficient safeguards and there were three we don't have, this being one. I think it's fine (good!) that it's a copy/paste. Just kinda how a lot of this goes

**Comment by mike-garcia** [comment]
@JTAGulous you still want to do this one?
