### ISSUE TITLE
bp_index.html Updates

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#178]
- [x] In Scope and Out of Scope is confusing. I think we should be explaining this better? Are all Priorities IN SCOPE? 
- [x] Let's throw ampersands into all these titles, we have "and" and "&" everywhere. I believe this is called parallelism 
- [ ] #210

**Comment by mike-garcia** [comment]
Links will have to wait, but I agree

**Comment by JTAGulous** [comment]
Moved the final bullet of making links to Q4.
