### ISSUE TITLE
maturity_bp_mapping.html Updates

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#179]
- [x] Small word insertion: This is about setting simple goals. " FOR EXAMPLE," complete one simple task a week, implement one best practice a month, and set aside a minimum set of resources dedicated to cybersecurity every quarter. Whatever helps you make progress.
- [x] I think we should break out Level 1 here and put it into it's own section under maturity. It would break the page up and make it easier to read. This is the most difficult page in the entire guide by a mile. We need to spend a lot of effort making this easier to understand. 
- [x] Maybe call this entire section "Putting it into practice" or "First Practical Steps" or "First Steps". I like First Steps.  
- [x] I find the "Action #1" thing confusing. There are multiple Action 1s and multiple Action 2s. What is happening. 
- [ ] The CDM stuff is meant to help for all levels. Maybe it should go into a "Methodology" section

**Comment by mike-garcia** [comment]
I could use a little help here:

- level 1 is broken out. do you mean it's own page? That's certainly doable
- yes, I don't like this either. Each best practice has multiple actions. Some of the worksheets only cover a subset of the level 1 actions for a a bp. So I want to communicate that completing the worksheet only gets some of the actions done and you still need to go do the others. Thoughts?
- I agree it applies to everything but I'm also trying to keep it simple for level 1. I think your suggestion works, though I'd want to spare the level 1 folks from having to get into it. Does that makes sense?

**Comment by mike-garcia** [comment]
moving to q4, but will likely pull back into an ad hoc update once we manage to reimagine the bp mapping page
