### ISSUE TITLE
Establish header and footer for PDF export

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#18]

**Comment by jungshadow** [comment]
@mike-garcia Hmm...this involves some understanding of LaTeX, which—I admit—is not my bread and butter. I'm sure I can do it, but it's gonna take me a lot more trial and error (i.e., more time).

**Comment by mike-garcia** [comment]
understood. it's in the soft launch milestone so hopefully that's enough. I saw something in some ReST documentation that made it seem like this was a build in feature, so we might get lucky. I have some latex experience but it's been forever so we can fumble through it together
