### ISSUE TITLE
README.html Updates 

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#181]
- [x] I believe this needs a new section about backward compatibility with the old guide. Also make this information available in a spreadsheet. 
- [ ] Maybe make the back and PREVIOUS and NEXT buttons bigger? 

**How do I use this Guide?**

- [x] I think this should mention the worksheets 
- [x] Perhaps this should be labeled DOCUMENT STRUCTURE 
- [x] Should we describe what's in a typical best practice page? 
- [x] Should we mention in the bottom left-hand corner they can download this document in PDF form? Also mention the worksheets and search function 

**A Little Encouragement Before You Start**

- [x] I'd say something about reaching out to CIS to provide feedback on this guide. “This guide is still in development, and CIS is interested in feedback from all readers. Ideas for content and usability improvements are most welcome; please email [elections@cisecurity.org](mailto:elections@cisecurity.org)”.

**Comment by mike-garcia** [comment]
I don't think there's anything I can do about the button sizes but I'll looking into whether that's customizable in RTD
