### ISSUE TITLE
Updates to User_Management.html

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#185]
- [x] I think the organization MFA stuff needs to be applied to users. They are included as “Organizational Recommendations” but IG1 applies some of the MFA to users. Users do have some responsibility since they often setup accounts with third party providers (even thought they probably shouldn’t” 
- [x] I’m worried this will be confusing. “…with reversible encryption.” It makes it sound like something special. I would just say “encryption”. 
- [x] CIS recommendations have the following which should be harmonized: 
o	For laptops, do not allow more than 20 failed authentication attempts; for tablets and smartphones, no more than 10 failed authentication attempts. Example implementations include Microsoft® InTune Device Lock and Apple® Configuration Profile maxFailedAttempts.

- [x] I would say under the “Ban or limit shared accounts section” that “Realistically, some devices or applications may require shared accounts. These accounts should receive formal exceptions from management and their usage appropriately tracked.” 
- [x] I think 3.3 3.3 Configure Data Access Control Lists should be included as IG1 or Maturity1 
- [x] I think 3.14 Log Sensitive Data Access might need to be included as Maturity 3 
- [x] We can probably do some links about these services. I thought CIS had a service? Use services to search for breaches of your users’ email addresses and passwords.

**Comment by mike-garcia** [comment]
I'm not aware of a CIS service but it exists lmk and I'll put it in
