### ISSUE TITLE
managing_staff.html Updates

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#187]
Links to add 

- [ ] MS-ISAC® Newsletter Subscription Newsletters, advisories, and webinars on cybersecurity threats
- [ ] MS-ISAC® Cybersecurity Awareness Toolkit Features educational materials designed to raise cybersecurity awareness. Digital materials are aggregated for your use
- [x] Federal Virtual Training Environment (FedVTE) Online Courses Free online cybersecurity training to State, Local, Tribal, and Territorial (SLTT) governments
- [ ] National Cyber Security Alliance (NCSA®) Nonprofit promoting cybersecurity awareness and education
- [ ] Security Awareness Toolbox Security awareness training resources
- [x] YouTube: StaySafeOnline.org Educational videos

**Comment by mike-garcia** [comment]
I included a couple of these but I don't think they are all great resources (NCSA runs staysafeonline, so I think it's best to just have sso). Not sure about the toolkit, it looks like an awareness month thing, but FedVTE was the relevant resource in it so I included just that one
