### ISSUE TITLE
patching_vuln_management Updates

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#190]
- [x] CIS Benchmarks™ Secure configuration guidelines for 100+ technologies, including operating systems, applications, and 
network devices
- [x] CIS SecureSuite® Membership No-cost membership to SLTTs, with access to CIS-CAT Pro Assessor, CIS Build Kits, CIS Benchmarks, and more
- [x] CIS-CAT® Pro Tool to scan for proper CIS Benchmark configurations for applications, operating systems, and network devices 
- [ ] CIS Build Kits ZIP files that contain a GPO for each profile within the corresponding CIS Benchmark 
- [ ] Local Group Policy Editor Microsoft Management Console (MMC) snap-in used to configure or modify Group Policy settings with Group Policy Objects (GPOs)
- [ ] OpenSCAP Ecosystem providing many tools to assist with assessment, measurement, and enforcement of baselines 
- [x] OpenVAS Framework for vulnerability scanning and management
- [ ] DISA STIGs A set of configuration guides developed and maintained by the U.S. Department of Defense (DoD) 
- [x] U.S. National Vulnerability Database (NVD) Repository of standards based on vulnerability management data
- [x] Nmap® Scripting Engine (NSE) Tool used for vulnerability scanning (including identified Common Vulnerabilities and Exposures (CVEs)) 
- [ ] Lynis Security audit tool used for system hardening 
- [ ] NIST SP 800-40 Rev. 4 Guide to Enterprise Patch Management Planning: Preventive Maintenance for Technology

**Comment by mike-garcia** [comment]
I added number of these,  but I wonder: at what point are we overloading them? For example, if someone is advanced enough to use STIGs, do they need to see them here at the expense of the less sophisticated clicking on something and giving up when they don't understand it?
