### ISSUE TITLE
Index of BPs.....Need to Present BPs in Prioritized Order

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#192]
All the BPs on the left are in alphabetical order. **This is madness**. Suggest a new order based off of the CIS Controls and ... our general feelings b/c it's subjective. But we can do better than alphabetical order .

I suggest this as a new beginning, based loosely off of the CIS Controls: 
Addressing Physical Threats
Asset Management
Patching and Vulnerability Management
Public Facing Network Scanning
Patching and Vulnerability Management
Managing Infrastructure
Backups
Endpoint Protection
Managing Removable Media
Managing Remote Connections

**Comment by mike-garcia** [comment]
I agree. I expected we would prioritize them at some point but hadn't reached that point. I figured CDM would be the way to go. Is there a reason you'd prefer control order?

**Comment by mike-garcia** [comment]
@JTAGulous ping!

**Comment by mike-garcia** [comment]
- [ ] update index
- [ ] put language in readme
- [ ] put language in bp_mapping to make clear that's the order

**Comment by mike-garcia** [comment]
- [ ] update bp_index

**Comment by mike-garcia** [comment]
Final ordering for 2022q3:

   bp/physical_threats
   bp/join_ei_isac
   bp/asset_management
   bp/encrypt_data_at_rest
   bp/managing_infrastructure
   bp/user_management
   bp/backups
   bp/incident_response
   bp/managing_staff
   bp/patching_vuln_management
   bp/remediate_pen_test_findings
   bp/internal_pentest
   bp/managing_remote_connections
   bp/firewalls_ports
   bp/endpoint_protection
   bp/mdbr
   bp/network_monitoring
   bp/wireless_management
   bp/public_asset_scanning
   bp/websites
   bp/removable_media
   bp/exercising_plans
   bp/formal_assessment
   bp/cis_controls
   bp/mdm_info
   bp/managing_vendors
