### ISSUE TITLE
auto-build in RTD

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#20]
Work with CIS to enable autobuild in RTD, or establish process (as automated as possible) to do so whenever main gets updated.

**Comment by mike-garcia** [comment]
update: I've got cis looking into these permissions

**Comment by jungshadow** [comment]
This is good to close, right, @mike-garcia?

**Comment by mike-garcia** [comment]
Yes!
