### ISSUE TITLE
Is media sanitization a priority?

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#22]
USB, etc, stuff is so prevalent for managing during an election cycle it seems to be a priority. 

@JTAGulous do you not agree? Is it 2nd level maturity? If so, do we give any removable media guidance to 1st level?

See [maturity mapping](../docs/source/Maturity/maturity_bp_mapping.rst) but note link might be messed up due to filename changes

**Comment by JTAGulous** [comment]
I think this is a reasonable one. I am not sure if it deserves to be a BP or just "another thing" of another BP. I'm open to it; let's explore and see what happens.
