### ISSUE TITLE
Types of Critical Election Files to Backup in Backup BP

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#32]
Should we list like ... top 5 types of files to backup? I'm thinking election specific things like VRDB, ballot definitions, and whatever the heck you call the GIS information used to decide which precinct gets what ballot? Other Jared would know what that's called.

**Comment by mike-garcia** [comment]
I think that makes sense. @jungshadow what do you think about this list? What's the GIS thingy called--if it's not just geocoding

**Comment by jungshadow** [comment]
You may have to simply specify any system that holds information on geopolitical boundaries, which may be separate from the VRDB...and it also may be the same system. In some cases, the data resides outside the purview of the elections office. I believe it's still the case in NYC that the geopolitical boundaries are held in the City Planner's office. Wisconsin's boundaries are determined/managed by the Legislative Technology Services Bureau. Thinking aloud, in regards to geopolitical shape files—i.e., not just the proprietary shapefile format, but any standard/system that specifies geopolitical boundaries—it may be useful to specify that the system backups should be both as system snapshots and as some standardized set of raw data.

**Comment by JTAGulous** [comment]
I like this answer @jungshadow. Super helpful. I've assigned to @JaredDearing for additional review :)

**Comment by mike-garcia** [comment]
fixed by #116

**Comment by mike-garcia** [comment]
That works for me!
