### ISSUE TITLE
Term: Ransomware 

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#33]
I saw malware was a term, perhaps ransomware should be too?

**Comment by mike-garcia** [comment]
That was just a test to see how the glossary worked. We do need to have a discussion about how much of a glossary we want to have.

At minimum I think CIS-specific terms, like Albert. We could do something more broadly, but it’s work and I’m not sure if we want to do that when other glossaries exist.

We’re also going to have an acronym list, so feel free to :term: any acronyms as well.

**Comment by JTAGulous** [comment]
Sounds great. I'll close this issue. The CIS Controls has a 4-page glossary of much argued-over terms that we can steal.
