### ISSUE TITLE
Device Asset Management BP Name 

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#35]
Do we want to just change this to "Asset Management" to include software (CIS Control 2)? Do we want to include management of subscriptions (e.g., Gmail, O365) and third-party service providers? Service Provider Management is CIS Control 15. I think we could do one ASSET MANAGEMENT BP and have it include all 3.

**Comment by mike-garcia** [comment]
That’s fine by me. If I remember right I was basing that off the SME guide. If you think we can do it cleanly without one bp being too large, I’m all for fewer BPs

**Comment by JTAGulous** [comment]
Excellent. I'll make the change!

**Comment by JTAGulous** [comment]
I changed the name and BP title. I will work to include the additional CIS Controls that are applicable.

**Comment by mike-garcia** [comment]
👍  fixed via #41
