### ISSUE TITLE
Patch Management vs Vulnerability Management

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#47]
Will we have a specific BP on vulnerability management or does it stop with patch management? The guidance for writing patch management gets awwwwwwfully close my good sirs 

* Readily identifies patches as they become available;
* Prioritizes patches for known vulnerable systems;
* Downloads patches from authoritative sources;
* Tests and verifies patches in the operating environment; and
* Applies appropriately tested patches to vulnerable systems.

**Comment by mike-garcia** [comment]
Actually prior to having seen this I just decided to collapse the two into one. We could call it both "Patching and vulnerability management" if that helps. Whatever you think is best

**Comment by mike-garcia** [comment]
Yes, plan was for that to be the only one
