### ISSUE TITLE
BP on training

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#64]
From Marci: 

> I would like to see a BP about training.  It may fit in the Managing Staff BP or be a standalone.  Election officials need understand they should create an environment of cyber awareness so all staff are thinking before they click.

**Comment by JTAGulous** [comment]
The CIS Controls have an area for Security Awareness and Training. I don't think that exactly covers it tho right? Or is that what we're looking for?

**Comment by mike-garcia** [comment]
We can certainly reference that but I think it’s more

**Comment by mike-garcia** [comment]
Add to managing_staff during phase 2 bp buildout
