### ISSUE TITLE
EDR Questions

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#69]
Can we say EDR should not be put on voting systems, but we DO want to put it on VR, blah, blah, blah, right? I'm not exactly sure what systems they should put it on. 

Also, stupid question: a small jurisdiction straight up can't afford EDR, right?

**Comment by mike-garcia** [comment]
on point 1, np, will implement

small jurisdictions can get them from free through EI-ISAC. Budgetary constraints result in a total cap EI-ISAC can give out for free, but we're not there yet. If we hit that, we'll need to think about updating; for now I think it's safe to say they can

**Comment by mike-garcia** [comment]
We’re promoting EDR to all jurisdictions, even the smallest. I do think there’s some election tech that is internet facing so we should message that anything on network connected is eligible
