### ISSUE TITLE
Fix internal referencing issues

### ISSUE THREAD

**Issue by jungshadow** [it-dept-cis/Essential-Guide-to-Election-Security#73]
You can technically do internal heading references two ways, but if you want it to work across platforms (and have it go through the usual Sphinx link QA), you'll want to make explicit—rather than implicit—references.

Example:

```rst
Each worksheet in the set is :ref:`described in the section below <it-inventory-worksheets>`.
You can also reference the `IT Inventory Worksheets`_ section directly, but that's discouraged.

.. _it-inventory-worksheets:

IT Inventory Worksheets
----------------------------------------------

There are six worksheets for IT Inventory.
```

We'll need to add explicit references to anything we want to cross reference from other parts of the doc. I'll add a PR as an example.

**Comment by mike-garcia** [comment]
all working now! thanks!
