### ISSUE TITLE
Guide looks and functions too good 

### ISSUE THREAD

**Issue by JTAGulous** [it-dept-cis/Essential-Guide-to-Election-Security#75]

**Comment by jungshadow** [comment]
![now-playing](https://user-images.githubusercontent.com/85972/165795104-e5f30d07-48cb-412e-a86a-fe274d911c0d.gif)

**Comment by mike-garcia** [comment]
This was a wonderful thing to see when unceremoniously woke up at 530a in a panic over the state of the guide. Thank you.
