### ISSUE TITLE
EI-ISAC logo on PDF

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#78]
currently it's CIS. lmk if you need the graphic

**Comment by mike-garcia** [comment]
Also both in the top left RTD header, if possible

**Comment by jungshadow** [comment]
This is (mostly) fixed. To your second point, there's currently not a way to stick more than one logo in the header—and I would caution against it. It's a fixed-size space made to be responsive on mobile and, aesthetically, they're two very different logos (and the logo that's there now is also used on the PDF). Unless a designer wants to experiment with how they could go together—and how that change translates to the PDF—I'd steer clear for now.

**Comment by jungshadow** [comment]
Closing for now (as this was fixed by #81), but feel free to reopen if you disagree.
