### ISSUE TITLE
Get dark mode versions of images

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#90]
- [x] https://images3.welcomesoftware.com/Zz1lNDc5YjA4NDg4NGIxMWVjODgwNmZhMTNlZjc2MjEzMg==

**Comment by jungshadow** [comment]
@mike-garcia, on looking at it in the browser, I thought this was the dark-mode image, but it actually has a transparent background, which is no different from the original.

**Comment by jungshadow** [comment]
Here are the dark-mode images we need:
- [ ] Malicious Domain Blocking and Reporting: MDBR-Simple-Secure-DNS-Diagram.22.01.png
- [ ] Endpoint Protection: EDR-Vendor-Cloud-Diagram.png
- [ ] Managing Remote Connections (NB: this image has a white background so it technically works as-is, but I feel it should match what we're doing on other pages): VPN.png

**Comment by mike-garcia** [comment]
submitted to marketing
